### ISSUE TITLE
依赖包安装时间比较慢

### ISSUE THREAD

**Issue by llh1347** [MILK2077/gzhu_clockIN#1]

**Comment by llh1347** [comment]
![IMG_20220401_222805](https://user-images.githubusercontent.com/68180007/161283748-85876060-247c-4e1b-88ce-1684a3d1f6ed.jpg)

**Comment by MILK2077** [comment]
是的，服务器每次都要重新下载webdriver比较花时间。但是我不认为这是个问题



---Original---
From: ***@***.***&gt;
Sent at: 2022年4月1日(Fri) Evening10:24
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [MILK2077/gzhu_clockIN] 依赖包安装时间比较慢 (Issue #1)

**Comment by MILK2077** [comment]
你能把日志给我看一下吗



---Original---
From: ***@***.***&gt;
Sent at: 2022年4月1日(Fri) Evening10:28
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [MILK2077/gzhu_clockIN] 依赖包安装时间比较慢 (Issue #1)

**Comment by llh1347** [comment]
脚本运行报错这个
Run python scraper.py


====== WebDriver manager ======
Current google-chrome version is 98.0.4758
Get LATEST chromedriver version for 98.0.4758 google-chrome
There is no [linux64] chromedriver for browser 98.0.4758 in cache
Trying to download new driver from https://chromedriver.storage.googleapis.com/98.0.4758.102/chromedriver_linux64.zip
Driver has been saved in cache [/home/runner/.wdm/drivers/chromedriver/linux64/98.0.4758.102]
登录融合门户成功！
Traceback (most recent call last):
  File "/home/runner/work/gzhu_clockIN/gzhu_clockIN/scraper.py", line 231, in <module>
    wd_login(xuhao, mima)
  File "/home/runner/work/gzhu_clockIN/gzhu_clockIN/scraper.py", line 121, in wd_login
    driver.get('https://yqtb.gzhu.edu.cn/infoplus/form/XNYQSB/start')
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 437, in get
    self.execute(Command.GET, {'url': url})
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/opt/hostedtoolcache/Python/3.9.10/x64/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: -0.003
  (Session info: headless chrome=98.0.4758.102)
Stacktrace:
#0 0x564ca6642b33 <unknown>
#1 0x564ca610b6d8 <unknown>
#2 0x564ca60f6f81 <unknown>
#3 0x564ca60f5ccf <unknown>
#4 0x564ca60f611c <unknown>
#5 0x564ca61040d0 <unknown>
#6 0x564ca6104ca2 <unknown>
#7 0x564ca611274d <unknown>
#8 0x564ca611584a <unknown>
#9 0x564ca60f6546 <unknown>
#10 0x564ca6112454 <unknown>
#11 0x564ca61721da <unknown>
#12 0x564ca615ef53 <unknown>
#13 0x564ca6134a0a <unknown>
#14 0x564ca6135ad5 <unknown>
#15 0x564ca66742fd <unknown>
#16 0x564ca668d4bb <unknown>
#17 0x564ca66760d5 <unknown>
#18 0x564ca668e145 <unknown>
#19 0x564ca6669aaf <unknown>
#20 0x564ca66aaba8 <unknown>
#21 0x564ca66aad28 <unknown>
#22 0x564ca66c548d <unknown>
#23 0x7f5564442609 <unknown>

Error: Process completed with exit code 1.

**Comment by MILK2077** [comment]
就是我划下划线的地方，能打开看看吗？
你不给我看报错信息我不好判断

---Original---
From: ***@***.***&gt;
Sent at: 2022年4月1日(Fri) Evening10:28
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: Re: [MILK2077/gzhu_clockIN] 依赖包安装时间比较慢 (Issue #1)

**Comment by MILK2077** [comment]
错误信息是说的请求https://yqtb.gzhu.edu.cn/infoplus/form/XNYQSB/start这个网址超时了。

**Comment by llh1347** [comment]
我看你部署的都成功了，我fork了原作者的运行后也是报错卡在一个地方

在 2022年4月2日，00:06，Lihao Deng ***@***.***> 写道：

﻿

错误信息是说的请求https://yqtb.gzhu.edu.cn/infoplus/form/XNYQSB/start这个网址超时了。<https://yqtb.gzhu.edu.cn/infoplus/form/XNYQSB/start%E8%BF%99%E4%B8%AA%E7%BD%91%E5%9D%80%E8%B6%85%E6%97%B6%E4%BA%86%E3%80%82>

**Comment by MILK2077** [comment]
请问你是说你现在运行这个脚本仍然失败吗

**Comment by MILK2077** [comment]
请问你是说在我修改了脚本后，你现在运行这个脚本仍然失败吗？你是否更新了项目？

**Comment by llh1347** [comment]
刚重新去看一小时前的运行提示成功了，这应该也是概率问题，像早上企业微信进入它也有概率提示报错，得设置多个时段跑脚本才行。玄学~

发件人: Lihao ***@***.***>
发送时间: 2022年4月2日 0:29
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [MILK2077/gzhu_clockIN] 依赖包安装时间比较慢 (Issue #1)


请问你是说在我修改了脚本后，你现在运行这个脚本仍然失败吗？你是否更新了项目？

―
